sonar.projectKey=amurlaniakea_hermes-shield
sonar.organization=amurlaniakea
sonar.projectName=Hermes Shield
sonar.projectVersion=0.2.0

sonar.sources=.
sonar.exclusions=tests/**,__pycache__/**,*.egg-info/**,.ruff_cache/**,.pytest_cache/**

sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.version=3.10,3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml
